### ISSUE TITLE
Opening Default Notebook

### ISSUE THREAD

**Issue by thecontinium** [prncss-xyz/neo-tree-zk.nvim#4]
I was expecting this `:Neotree source=zk dir=$ZK_NOTEBOOK_DIR` to open the default notebook ?

**Comment by thecontinium** [comment]
I only have one notebook and it is defined using `ZK_NOTEBOOK_DIR` set to `/Users/thecontinium/Library/Mobile Documents/7CRMDf45sG~com~ngocluu~onewriter/Documents/notes`.

What I am seeing is that if `cwd` is anywhere in this path to my notes i.e. `/Users`, `/Users/thecontinium`, `/Users/thecontinium/Library`, etc.  then `:Neotree source=zk` shows the notes in the tree relative to `cwd`.

If `cwd` is anywhere outside of this path e.g. `/Users/thecontinium/dev` then `:Neotree source=zk` shows an **empty** tree. 

Is this what you would expect ?

Ideally for me the tree would follow the same [discovery](https://github.com/mickael-menu/zk-nvim#notebook-directory-discovery) of notebooks as zk-nvim. 

Is this what you envisage or do you see it working a different way ?

**Comment by prncss-xyz** [comment]
Yup, I'm implementing just that discovery heuristics right now! (But also making use of the `dir` param when specified, as you pointed.) Should be ready today or next week. Thanks for pushing upwards! :-)

**Comment by prncss-xyz** [comment]
Should work fine by now.

**Comment by thecontinium** [comment]
looking good - works for me. thanks
